// Code generated by ogen, DO NOT EDIT.
package oas

type AddIncidentRes interface {
	addIncidentRes()
}

type CheckUserRes interface {
	checkUserRes()
}

type DeleteIncidentRes interface {
	deleteIncidentRes()
}

type GetIncidentByIdRes interface {
	getIncidentByIdRes()
}

type GetIncidentsRes interface {
	getIncidentsRes()
}

type GetStatusesRes interface {
	getStatusesRes()
}

type GetUserByIdRes interface {
	getUserByIdRes()
}

type GetUserRes interface {
	getUserRes()
}

type GetUsersRes interface {
	getUsersRes()
}

type LogoutRes interface {
	logoutRes()
}

type UpdateIncidentRes interface {
	updateIncidentRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
