// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	IncidentsHandler
}

// IncidentsHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Incidents
type IncidentsHandler interface {
	// AddIncidents implements addIncidents operation.
	//
	// Add a new incidents.
	//
	// POST /incidents
	AddIncidents(ctx context.Context, req AddIncidentsReq) (AddIncidentsRes, error)
	// DeleteIncident implements deleteIncident operation.
	//
	// Delete an incidents.
	//
	// DELETE /incidents/{incidentId}
	DeleteIncident(ctx context.Context, params DeleteIncidentParams) (DeleteIncidentRes, error)
	// GetIncidentById implements getIncidentById operation.
	//
	// Returns a single incidents.
	//
	// GET /incidents/{incidentId}
	GetIncidentById(ctx context.Context, params GetIncidentByIdParams) (GetIncidentByIdRes, error)
	// GetIncidents implements getIncidents operation.
	//
	// List of incidents.
	//
	// GET /incidents
	GetIncidents(ctx context.Context) (GetIncidentsRes, error)
	// UpdateIncidents implements updateIncidents operation.
	//
	// Update an existing incidents by Id.
	//
	// PUT /incidents
	UpdateIncidents(ctx context.Context, req UpdateIncidentsReq) (UpdateIncidentsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
