// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddIncidents implements addIncidents operation.
//
// Add a new incidents.
//
// POST /incidents
func (UnimplementedHandler) AddIncidents(ctx context.Context, req AddIncidentsReq) (r AddIncidentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteIncident implements deleteIncident operation.
//
// Delete an incidents.
//
// DELETE /incidents/{incidentId}
func (UnimplementedHandler) DeleteIncident(ctx context.Context, params DeleteIncidentParams) error {
	return ht.ErrNotImplemented
}

// GetIncidentById implements getIncidentById operation.
//
// Returns a single incidents.
//
// GET /incidents/{incidentId}
func (UnimplementedHandler) GetIncidentById(ctx context.Context, params GetIncidentByIdParams) (r GetIncidentByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIncidents implements getIncidents operation.
//
// List of incidents.
//
// GET /incidents
func (UnimplementedHandler) GetIncidents(ctx context.Context) (r GetIncidentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateIncidents implements updateIncidents operation.
//
// Update an existing incidents by Id.
//
// PUT /incidents
func (UnimplementedHandler) UpdateIncidents(ctx context.Context, req UpdateIncidentsReq) (r UpdateIncidentsRes, _ error) {
	return r, ht.ErrNotImplemented
}
