// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	AddIncidentsOperation    OperationName = "AddIncidents"
	AddStatusOperation       OperationName = "AddStatus"
	CheckSmsOperation        OperationName = "CheckSms"
	CheckUserOperation       OperationName = "CheckUser"
	DeleteIncidentOperation  OperationName = "DeleteIncident"
	DeleteStatusOperation    OperationName = "DeleteStatus"
	GetIncidentByIdOperation OperationName = "GetIncidentById"
	GetIncidentsOperation    OperationName = "GetIncidents"
	GetStatusByIdOperation   OperationName = "GetStatusById"
	GetStatusesOperation     OperationName = "GetStatuses"
	GetUserOperation         OperationName = "GetUser"
	LogoutOperation          OperationName = "Logout"
	SendSmsOperation         OperationName = "SendSms"
	UpdateIncidentsOperation OperationName = "UpdateIncidents"
	UpdateStatusOperation    OperationName = "UpdateStatus"
)
