// Code generated by ogen, DO NOT EDIT.

package oas

// setDefaults set default value of fields.
func (s *IncidentResponse) setDefaults() {
	{
		val := string("Ok")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *IncidentsResponse) setDefaults() {
	{
		val := string("Ok")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *StatusesResponse) setDefaults() {
	{
		val := string("Ok")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *UserResponse) setDefaults() {
	{
		val := string("Ok")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *UsersResponse) setDefaults() {
	{
		val := string("Ok")
		s.Status = val
	}
}
