// Code generated by ogen, DO NOT EDIT.

package oas

// setDefaults set default value of fields.
func (s *IncidentsResponse) setDefaults() {
	{
		val := string("Ok")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *StatususResponse) setDefaults() {
	{
		val := string("Ok")
		s.Status = val
	}
}
