// Code generated by ogen, DO NOT EDIT.
package oas

type AddIncidentRes interface {
	addIncidentRes()
}

type DeleteIncidentRes interface {
	deleteIncidentRes()
}

type GetIncidentByIdRes interface {
	getIncidentByIdRes()
}

type GetIncidentsRes interface {
	getIncidentsRes()
}

type GetStatusesRes interface {
	getStatusesRes()
}

type UpdateIncidentRes interface {
	updateIncidentRes()
}
