// Code generated by ogen, DO NOT EDIT.
package oas

type AddIncidentsReq interface {
	addIncidentsReq()
}

type AddIncidentsRes interface {
	addIncidentsRes()
}

type AddStatusReq interface {
	addStatusReq()
}

type AddStatusRes interface {
	addStatusRes()
}

type CheckSmsRes interface {
	checkSmsRes()
}

type DeleteIncidentRes interface {
	deleteIncidentRes()
}

type DeleteStatusRes interface {
	deleteStatusRes()
}

type GetIncidentByIdRes interface {
	getIncidentByIdRes()
}

type GetIncidentsRes interface {
	getIncidentsRes()
}

type GetStatusByIdRes interface {
	getStatusByIdRes()
}

type GetStatusesRes interface {
	getStatusesRes()
}

type GetUserRes interface {
	getUserRes()
}

type LogoutRes interface {
	logoutRes()
}

type SendSmsRes interface {
	sendSmsRes()
}

type UpdateIncidentsReq interface {
	updateIncidentsReq()
}

type UpdateIncidentsRes interface {
	updateIncidentsRes()
}

type UpdateStatusReq interface {
	updateStatusReq()
}

type UpdateStatusRes interface {
	updateStatusRes()
}
