// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	AddIncidentOperation     OperationName = "AddIncident"
	DeleteIncidentOperation  OperationName = "DeleteIncident"
	GetIncidentByIdOperation OperationName = "GetIncidentById"
	GetIncidentsOperation    OperationName = "GetIncidents"
	GetStatusesOperation     OperationName = "GetStatuses"
	UpdateIncidentOperation  OperationName = "UpdateIncident"
)
